/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FishMarketRouteImport } from './routes/fish-market'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShipyardRouteImport } from './routes/shipyard'
import { Route as TribesRouteImport } from './routes/tribes'
import { Route as VillageIdRouteImport } from './routes/village.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FishMarketRoute = FishMarketRouteImport.update({
  id: '/fish-market',
  path: '/fish-market',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipyardRoute = ShipyardRouteImport.update({
  id: '/shipyard',
  path: '/shipyard',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesRoute = TribesRouteImport.update({
  id: '/tribes',
  path: '/tribes',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageIdRoute = VillageIdRouteImport.update({
  id: '/village/$id',
  path: '/village/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/fish-market': typeof FishMarketRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/shipyard': typeof ShipyardRoute
  '/tribes': typeof TribesRoute
  '/village/$id': typeof VillageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/fish-market': typeof FishMarketRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/shipyard': typeof ShipyardRoute
  '/tribes': typeof TribesRoute
  '/village/$id': typeof VillageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/fish-market': typeof FishMarketRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/shipyard': typeof ShipyardRoute
  '/tribes': typeof TribesRoute
  '/village/$id': typeof VillageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/fish-market'
    | '/friends'
    | '/settings'
    | '/shipyard'
    | '/tribes'
    | '/village/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/fish-market'
    | '/friends'
    | '/settings'
    | '/shipyard'
    | '/tribes'
    | '/village/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/fish-market'
    | '/friends'
    | '/settings'
    | '/shipyard'
    | '/tribes'
    | '/village/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  FishMarketRoute: typeof FishMarketRoute
  FriendsRoute: typeof FriendsRoute
  SettingsRoute: typeof SettingsRoute
  ShipyardRoute: typeof ShipyardRoute
  TribesRoute: typeof TribesRoute
  VillageIdRoute: typeof VillageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish-market': {
      id: '/fish-market'
      path: '/fish-market'
      fullPath: '/fish-market'
      preLoaderRoute: typeof FishMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipyard': {
      id: '/shipyard'
      path: '/shipyard'
      fullPath: '/shipyard'
      preLoaderRoute: typeof ShipyardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes': {
      id: '/tribes'
      path: '/tribes'
      fullPath: '/tribes'
      preLoaderRoute: typeof TribesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village/$id': {
      id: '/village/$id'
      path: '/village/$id'
      fullPath: '/village/$id'
      preLoaderRoute: typeof VillageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  FishMarketRoute: FishMarketRoute,
  FriendsRoute: FriendsRoute,
  SettingsRoute: SettingsRoute,
  ShipyardRoute: ShipyardRoute,
  TribesRoute: TribesRoute,
  VillageIdRoute: VillageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
